feat: 봉사자 출석 상태 수정 로직을 구현한다.
Anifriends/Anifriends-Backend pull request #171
Opened 2023-11-09 15:27 UTC by pushedrumex

### ⛏ 작업 사항
봉사자 출석 상태 수정 로직을 구현했습니다.

### 📝 작업 요약
- Applicant 의 status 업데이트를 위한  Bulk update 쿼리 구현
- Applicant status 업데이트 레포지토리 테스트코드 작성
- Applicant status 업데이트 서비스 구현 및 테스트코드 작성
- Applicant status 업데이트 컨트롤러 구현 및 테스트코드 작성

### 💡 관련 이슈
- close #106

2023-11-09 15:40 UTC, hseong3243 requested changes
고생하셨습니다. 코멘트 확인해주세요!

2023-11-09 15:40 UTC, hseong3243 commented on src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
> +        + "then 'ATTENDANCE' else 'NO_SHOW' end "
case when then을 피해서 서비스 로직에서 처리할 수 있을까요?
불가피한 경우가 아니라면 신청자의 상태가 변경되는 것을 결정하는 로직은 쿼리문이 아닌 서비스 로직에 존재해야 한다고 생각합니다!

2023-11-09 15:46 UTC, hseong3243 commented
> 고생하셨습니다. 코멘트 확인해주세요!

2023-11-09 15:54 UTC, pushedrumex commented on src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
> +        + "then 'ATTENDANCE' else 'NO_SHOW' end "
만약 한 개의 봉사자 상태 변경 요청일 경우에는 말씀하신 방법대로 했을 것 같습니다. 하지만, 서비스 로직에서 처리할 경우 100명의 신청자가 있을 때, Applicant 하나씩 status 를 변경해준 후 save를 해야해서 100개의 update 쿼리가 발생하게되어서 Bulk update 쿼리를 사용하는게 현재의 상황에서 적절하다고 생각했습니다🤔

2023-11-09 16:40 UTC, hseong3243 commented on src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
> +        + "then 'ATTENDANCE' else 'NO_SHOW' end "
당연히 어떤 방법이든 벌크 업데이트를 사용하기는 해야 합니다! 다만 case when을 사용하여 쿼리 안에서 사용자를 분류하는 것이 적절한가? 라는 생각이 듭니다.
하지만 서비스 로직에서 분류하면 벌크 업데이트 쿼리를 2번은 날려야 할 것 같아서... 성능을 고려한다면 case when을 사용해서 쿼리가 1번 나가는 것이 나을 수 있겠네요.

2023-11-09 16:41 UTC, hseong3243 approved these changes

2023-11-09 17:49 UTC, pushedrumex commented on src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
> +        + "then 'ATTENDANCE' else 'NO_SHOW' end "
아하 그런 의미였군요! 제가 이해를 잘못했네요😅

말씀하신대로 attendedIds와 noShowIds 리스트를 서비스단에서 분류해서 벌크 업데이트를 하는 방향이 더 적절할 듯 합니다! 👍

2023-11-10 06:50 UTC, bjo6300 approved these changes
👍🏻

2023-11-10 06:50 UTC, bjo6300 commented on src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
> +        + "case when a.applicantId in :attendedIds "
JPQL에서 case when then이 가능하군요! 배워갑니당

2023-11-10 07:32 UTC, bjo6300 approved these changes

2023-11-10 07:32 UTC, bjo6300 commented on src/main/java/com/clova/anifriends/domain/applicant/controller/ApplicantController.java
> +        @RequestBody UpdateApplicantsAttendanceRequest request
`파라미터 이름 또한 request가 아닌 풀네임으로 적는다.` 
코드 컨벤션 확인해주세요😄

2023-11-11 05:36 UTC, funnysunny08 approved these changes
👍👍

2023-11-11 08:43 UTC, merged