feat: 사용자 인증을 위한 jwt 인증 프로세스를 구현한다.
Anifriends/Anifriends-Backend pull request #41
Opened 2023-10-31 16:10 UTC by hseong3243

### ⛏ 작업 사항
- 미리 구현해놓은 jwt 인증 로직을 프로젝트에 적용하였습니다.
- 저희 프로젝트에 맞게 해당 사항을 커스텀하였습니다.
- 로그인한 사용자의 id 값이 필요한 경우 컨트롤러 메서드의 파라미터에 `@LoginUser` 어노테이션을 사용해주시면 됩니다. `LoginArgumentResolver`가 `SecurityContext`로부터 인증 객체를 꺼내고, 인증 객체에 들어있는 로그인한 사용자 id 값을 가져옵니다.
- 리프레시 토큰을 이용한 액세스 토큰 갱신 로직은 존재하나 리프레시 토큰 전송 방법에 쿠키를 사용할지 다른 방법을 사용할지 보류 중이라 추후 적용 예정입니다.

### 📝 작업 요약
- JWT 인증 로직 템플릿 적용 및 커스텀

### 💡 관련 이슈
- close #8

2023-10-31 16:34 UTC, bjo6300 submitted a review, later dismissed

2023-10-31 16:34 UTC, bjo6300 commented on src/main/java/com/clova/anifriends/domain/auth/controller/request/LoginRequest.java
> +    @NotBlank
message 적어주면 더 좋을 것 같아요!

2023-10-31 19:17 UTC, bjo6300 submitted a review, later dismissed

2023-10-31 19:17 UTC, bjo6300 commented on src/main/java/com/clova/anifriends/domain/volunteer/repository/VolunteerRepository.java
> +    Optional<Volunteer> findByEmail(VolunteerEmail email);
레포지토리 테스트 코드가 없는 것 같아요!

2023-11-01 01:50 UTC, hseong3243 commented on src/main/java/com/clova/anifriends/domain/volunteer/repository/VolunteerRepository.java
> +    Optional<Volunteer> findByEmail(VolunteerEmail email);
쿼리 메서드는 빌드 테스트만 돌려도 정상적으로 작성했는지 파악할 수 있어서 따로 테스트를 작성하지는 않았습니다!

2023-11-01 04:51 UTC, pushedrumex requested changes

2023-11-01 04:51 UTC, pushedrumex commented on src/test/java/com/clova/anifriends/domain/auth/jwt/JJwtProviderTest.java
> +        void success() {
`성공하는 테스트의 경우 테스트 대상 메서드의 이름을 적도록 한다.` 테스트 컨벤션 확인해주세요😊
https://www.notion.so/prgrms/109454cbbde44644953c508be97a5272

2023-11-01 04:51 UTC, pushedrumex commented on src/test/java/com/clova/anifriends/domain/auth/jwt/JJwtProviderTest.java
> +}
전체적으로 개행 빠져있는곳 수정해주세요😊

2023-11-01 04:51 UTC, pushedrumex commented on src/test/java/com/clova/anifriends/domain/auth/jwt/JJwtProviderTest.java
> +                .isInstanceOf(ExpiredRefreshTokenException.class);
```suggestion
            // when
            Exception exception = catchException(
                () -> jJwtProvider.refreshAccessToken(expiredRefreshToken)));

            // then
            assertThat(exception).isInstanceOf(ExpiredRefreshTokenException.class);
```

로 excpetion을 then절에서 assert 하면 given/then 절이 더 명확해질것같습니다!

2023-11-01 04:51 UTC, pushedrumex commented on src/test/java/com/clova/anifriends/domain/auth/service/AuthServiceTest.java
> +            given(shelterRepository.findByEmail(any())).willReturn(Optional.ofNullable(shelter));
any() 를 shelterId나 anyLong()으로 수정하면 좋을 것 같습니다!

2023-11-01 09:41 UTC, bjo6300 approved these changes

2023-11-01 09:58 UTC, funnysunny08 approved these changes

2023-11-01 09:59 UTC, pushedrumex approved these changes
고생하셨습니당

2023-11-01 09:59 UTC, merged