feat: 보호소 프로필 조회 API를 구현한다.
Anifriends/Anifriends-Backend pull request #45
Opened 2023-10-31 18:15 UTC by bjo6300

### ⛏ 작업 사항
보호소 프로필 조회 API를 구현했습니다.

### 📝 작업 요약
- 보호소 프로필 조회 서비스 구현
- 보호소 프로필 조회 서비스 테스트 코드 작성
- 보호소 프로필 조회 컨트롤러 구현
- 보호소 프로필 조회 컨트롤러 테스트 코드 작성

### 💡 관련 이슈
- close #29

2023-10-31 19:18 UTC, pushedrumex requested changes

2023-10-31 19:18 UTC, pushedrumex commented on src/test/java/com/clova/anifriends/domain/shelter/controller/ShelterControllerTest.java
> +            .andDo(print())
Base 에 있어서 생략해도 될 것 같아요!

2023-10-31 19:18 UTC, pushedrumex commented on src/test/java/com/clova/anifriends/domain/shelter/service/ShelterServiceTest.java
> +                foundShelterDetailResponse.imageUrl());
```suggestion
assertThat(givenShelter).usingRecursiveComparison().isEqualTo(response);
```

2023-10-31 19:18 UTC, pushedrumex commented on src/test/java/com/clova/anifriends/domain/shelter/service/ShelterServiceTest.java
> +                .isInstanceOf(ShelterNotFoundException.class);
```suggestion
            // when
            Exception exception = catchException(
                () -> shelterService.findShelterDetail(shelterId));

            // then
            assertThat(exception).isInstanceOf(ShelterNotFoundException.class);
```

로 하면 given과 then 절의 구분이 명확해질 것 같아요!

2023-10-31 19:18 UTC, pushedrumex commented on src/test/java/com/clova/anifriends/domain/shelter/service/ShelterServiceTest.java
> +            assertThatThrownBy(() -> shelterService.findShelterDetail(shelterImageId))
이것도 Exception 따로 assert하면 좋을 것 같습니다😊

2023-10-31 19:18 UTC, pushedrumex commented on src/test/java/com/clova/anifriends/domain/shelter/service/ShelterServiceTest.java
> +        givenShelterImage = ShelterImageFixture.shelterImage(givenShelter);
beforeEach 를 사용하기보단 각 테스트 마다 필요한 fixture를 정의해서 사용하는게 어떨까요??

2023-10-31 19:20 UTC, bjo6300 commented on src/main/java/com/clova/anifriends/domain/shelter/service/ShelterService.java
> +                () -> new ShelterNotFoundException(ErrorCode.NOT_FOUND, "존재하지 않는 보호소입니다."));
좋은 것 같아요!

2023-10-31 19:21 UTC, bjo6300 commented on src/main/java/com/clova/anifriends/domain/shelter/service/ShelterService.java
> +                "존재하지 않는 보호소 이미지입니다."));
좋은 생각인 것 같아요! OneToOne 관계인 보호소, 봉사자의 이미지 테이블에 대해서 팀원분들이랑 이야기해봐요~

2023-10-31 19:23 UTC, bjo6300 commented on src/test/java/com/clova/anifriends/domain/shelter/controller/ShelterControllerTest.java
> +        given(shelterService.findShelterDetail(any())).willReturn(findShelterDetailResponse);
아 그러네요 감사합니다!

2023-11-01 02:11 UTC, hseong3243 commented on src/main/java/com/clova/anifriends/domain/shelter/Shelter.java
> +    public Boolean getIsOpenedAddress() {
반환값이 boolean 이라면 isOpenedAddress() 라는 이름이면 더 좋을 것 같습니다!

2023-11-01 02:11 UTC, hseong3243 commented on src/test/java/com/clova/anifriends/domain/shelter/controller/ShelterControllerTest.java
> +        given(shelterService.findShelterDetail(any())).willReturn(findShelterDetailResponse);
저는 shelterId가 로직의 핵심 요소가 아니라면 any()를 인자로 전달해도 괜찮다고 생각합니다!

2023-11-01 02:11 UTC, hseong3243 commented on src/test/java/com/clova/anifriends/domain/shelter/repository/ShelterImageRepositoryTest.java
> +@DataJpaTest
부모 클래스에 `@DataJpaTest`가 달려있기때문에 굳이 붙여주지 않으셔도 됩니다!

2023-11-01 03:32 UTC, funnysunny08 approved these changes

2023-11-01 04:55 UTC, pushedrumex commented on src/test/java/com/clova/anifriends/domain/shelter/controller/ShelterControllerTest.java
> +        given(shelterService.findShelterDetail(any())).willReturn(findShelterDetailResponse);
해당 컨트롤러에서 서비스를 호출했을 때 shelterService.findShelterDetail(long shelterId)에 대한 반환 값이 shelterId가 1인 것의 응답일텐데, shelter의 id를 넣어주는게 적절하지 않을까용??

2023-11-01 08:15 UTC, bjo6300 commented on src/test/java/com/clova/anifriends/domain/shelter/service/ShelterServiceTest.java
> +        givenShelterImage = ShelterImageFixture.shelterImage(givenShelter);
독립적인 테스트를 위한거군요! 반영하겠습니다

2023-11-01 09:12 UTC, hseong3243 commented on src/test/java/com/clova/anifriends/domain/shelter/controller/ShelterControllerTest.java
> +        given(shelterService.findShelterDetail(any())).willReturn(findShelterDetailResponse);
음. 다시 한 번 보니까 여기서는 넣어도 좋을 것 같습니다!

2023-11-01 10:02 UTC, pushedrumex approved these changes
고생하셨습니당!

2023-11-01 13:37 UTC, hseong3243 approved these changes
고생하셨습니다!

2023-11-01 13:38 UTC, merged