feat: 봉사자가 신청한 봉사 리스트 조회 로직을 구현한다.
Anifriends/Anifriends-Backend pull request #87
Opened 2023-11-04 09:29 UTC by bjo6300

### ⛏ 작업 사항
- 봉사자가 신청한 봉사 리스트 조회 쿼리, 서비스, 컨트롤러 코드 작성 및 테스트 코드 작성

### 📝 작업 요약
- 봉사자가 신청한 봉사 리스트 조회 로직을 구현

### 💡 관련 이슈
- close #77

2023-11-04 11:54 UTC, hseong3243 requested changes
고생하셨습니다! 코멘트 확인해주세요!

2023-11-04 11:54 UTC, hseong3243 commented on src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplyingVolunteersResponse.java
> +                && Objects.isNull(applicant.getReview())) {
후기를 썼는지 판단하는 로직은 dto를 만드는 로직과 분리하는게 어떨까요? 서비스 로직에서 판단하거나 applicant 내부적으로 판단하는 것이 더 파악하기 좋을 것 같습니다!

2023-11-04 15:36 UTC, bjo6300 commented on src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplyingVolunteersResponse.java
> +                && Objects.isNull(applicant.getReview())) {
applicant 내부에서 판단하는 방법 좋은 것 같아요 👍🏻 수정했습니다! (c57897118f0051c1611c4544c0380d447aee9595)

2023-11-04 16:02 UTC, funnysunny08 approved these changes
수고하셨습니다!!

2023-11-04 16:18 UTC, pushedrumex commented on src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
> +        return getStatus().equals(ApplicantStatus.ATTENDANCE) && Objects.isNull(getReview());
getReview() 를 호출하지 않고 바로 review 를 사용해도 될 것 같습니다!

2023-11-04 16:18 UTC, pushedrumex commented on src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
> +    public boolean shouldWriteReview() {
메서드명을 noReview 로하는게 어떨까요?? (참고로 저는 hasReview 로 했습니다😀)

2023-11-04 16:18 UTC, pushedrumex commented on src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplyingVolunteersResponse.java
> +    public record FindApplyingVolunteerResponse(
```suggestion
    private record FindApplyingVolunteerResponse(
```

2023-11-04 16:18 UTC, pushedrumex commented on src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplyingVolunteersResponse.java
> +        public static FindApplyingVolunteerResponse from(
```suggestion
        private static FindApplyingVolunteerResponse from(
```

2023-11-04 16:18 UTC, pushedrumex commented on src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
> +            + "left join fetch a.review "
그냥 join fetch 를 해도 되지 않나요??

2023-11-04 16:29 UTC, bjo6300 commented on src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
> +    public boolean shouldWriteReview() {
hasNotReview로 통일하는 방법은 어떠신가요??

2023-11-04 16:36 UTC, bjo6300 commented on src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplyingVolunteersResponse.java
> +    public record FindApplyingVolunteerResponse(
![image](https://github.com/Anifriends/Anifriends-Backend/assets/70627982/b26f909f-1c0e-45bf-965c-00f96b6df763)
private으로 하면 내부 값에 접근을 하지 못합니다...! dto인데 private으로 하는 이유가 있으신가요??

2023-11-04 16:39 UTC, pushedrumex commented on src/main/java/com/clova/anifriends/domain/applicant/Applicant.java
> +    public boolean shouldWriteReview() {
좋아요!

2023-11-04 16:42 UTC, pushedrumex commented on src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplyingVolunteersResponse.java
> +    public record FindApplyingVolunteerResponse(
FindApplyingVolunteerResponse 는 FindApplyingVolunteersResponse 내부에서만 사용하는 dto 여서 내부 dto 는 외부에서 접근하지 못하도록 private 으로 선언하는게 적절할 것 같아요!

2023-11-04 16:47 UTC, bjo6300 commented on src/main/java/com/clova/anifriends/domain/applicant/repository/ApplicantRepository.java
> +            + "left join fetch a.review "
recruitment, volunteer는 join fetch를 해도 상관없지만 review는 reviewId가 null인 값을 가져오기 위해 left join을 적용했습니다!

2023-11-04 16:55 UTC, bjo6300 commented on src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplyingVolunteersResponse.java
> +    public record FindApplyingVolunteerResponse(
![image](https://github.com/Anifriends/Anifriends-Backend/assets/70627982/4498fc2f-f763-492e-84bd-34cbb0342a27)

`ApplicantServiceTest`의 `FindApplyingVolunteersTest`입니다!

2023-11-05 07:45 UTC, bjo6300 commented on src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplyingVolunteersResponse.java
> +    public record FindApplyingVolunteerResponse(
```
public record FindApplyingVolunteersResponse(
    List<FindApplyingVolunteerResponse> findApplyingVolunteerResponses
) {

    public record FindApplyingVolunteerResponse(
        Long recruitmentId,
        Long applicantId,
        String title,
        String shelterName,
        ApplicantStatus status,
        boolean isWritedReview,
        LocalDateTime volunteerDate
    ) {

        public static FindApplyingVolunteerResponse from(
            Applicant applicant
        ) {
            return new FindApplyingVolunteerResponse(
                applicant.getRecruitment().getRecruitmentId(),
                applicant.getApplicantId(),
                applicant.getRecruitment().getTitle(),
                applicant.getRecruitment().getShelter().getName(),
                applicant.getStatus(),
                applicant.hasNotReview(),
                applicant.getRecruitment().getStartTime()
            );
        }
    }

    public static FindApplyingVolunteersResponse from(
        List<Applicant> applicants
    ) {
        return new FindApplyingVolunteersResponse(
            applicants
                .stream()
                .map(FindApplyingVolunteerResponse::from)
                .toList()
        );
    }
}
```

`public record FindApplyingVolunteerResponse` 이 부분을 `private`으로 변경하면 리스트 내의 값 비교 시 접근을 못합니다.

assertThat(foundApplyingVolunteers.findApplyingVolunteerResponses().`get(0)`
    .isWritedReview()).isEqualTo(
    findApplyingVolunteersResponse.findApplyingVolunteerResponses().`get(0)`
        .isWritedReview());

여기서 get을 하지 못하므로 테스트를 하려면 `usingRecursiveComparison`을 사용해야하는데, 정확한 값을 확인하지 못하고 `usingRecursiveComparison` 함수에 의존하는건 무엇을 검증하고자 하는지 테스트를 하기 힘들다고 생각합니다. 🥲

2023-11-05 09:14 UTC, hseong3243 commented on src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplyingVolunteersResponse.java
> +    public record FindApplyingVolunteerResponse(
dto까지 클래스 접근제어자를 private으로 할 필요는 없을 것 같습니다. 특정 값 하나만 검증을 목표로 하는 테스트라면 해당 값에 접근하기 위한 과정이 너무 불필요하게 길어질 것 같아요!
만약 비즈니스 로직에서 쓰이기 위한 클래스라면 내부에 정적으로 선언한 클래스에 접근이 불필요하다고 판단되는 경우 private으로 막는게 옳겠습니다.
하지만 클라이언트에게 단순히 값을 반환하기 위해 사용하는 dto까지 접근을 막아버릴 필요는 없다고 생각합니다!

2023-11-06 08:26 UTC, pushedrumex approved these changes

2023-11-06 13:48 UTC, bjo6300 commented on src/main/java/com/clova/anifriends/domain/applicant/dto/FindApplyingVolunteersResponse.java
> +    public record FindApplyingVolunteerResponse(
스크럼 시간에 토론해봐요~!

2023-11-06 15:53 UTC, hseong3243 approved these changes
🚀

2023-11-06 15:54 UTC, merged